l_shoulder_pitch_controller:
  controller:
    package: dynamixel_manipulation
    module: joint_position_controller
    type: JointPositionController
  joint_name: l_shoulder_pitch_joint
  joint_speed: 1.17
  motor:
    id: 4
    init: 1000
    min: 0
    max: 1023

l_shoulder_pan_controller:
  controller:
    package: dynamixel_manipulation
    module: joint_position_controller
    type: JointPositionController
  joint_name: l_shoulder_pan_joint
  joint_speed: 1.17
  motor:
    id: 5
    init: 1000
    min: 0
    max: 1023

l_elbow_pan_controller:
  controller:
    package: dynamixel_manipulation
    module: joint_position_controller
    type: JointPositionController
  joint_name: l_elbow_pan_joint
  joint_speed: 1.17
  motor:
    id: 6
    init: 1000
    min: 0
    max: 1023

l_foream_roll_controller:
  controller:
    package: dynamixel_manipulation
    module: joint_position_controller
    type: JointPositionController
  joint_name: l_foream_roll_joint
  joint_speed: 1.17
  motor:
    id: 7
    init: 1000
    min: 0
    max: 1023

l_wrist_pitch_controller:
  controller:
    package: dynamixel_manipulation
    module: joint_position_controller
    type: JointPositionController
  joint_name: l_wrist_pitch_joint
  joint_speed: 1.17
  motor:
    id: 8
    init: 1000
    min: 0
    max: 1023

l_wrist_roll_controller:
  controller:
    package: dynamixel_manipulation
    module: joint_position_controller
    type: JointPositionController
  joint_name: l_wrist_roll_joint
  joint_speed: 1.17
  motor:
    id: 9
    init: 1000
    min: 0
    max: 1023

l_end_effector_controller:
  controller:
    package: dynamixel_manipulation
    module: joint_position_controller
    type: JointPositionController
  joint_name: l_end_effector_joint
  joint_speed: 1.17
  motor:
    id: 10
    init: 100000
    min: 0
    max: 1023;

l_waist_pitch_controller:
  controller:
    package: dynamixel_manipulation
    module: joint_position_controller
    type: JointPositionController
  joint_name: l_end_effector_joint
  joint_speed: 1.17
  motor:
    id: 30
    init: 100000
    min: 0
    max: 1023;

l_waist_pan_controller:
  controller:
    package: dynamixel_manipulation
    module: joint_position_controller
    type: JointPositionController
  joint_name: l_end_effector_joint
  joint_speed: 1.17
  motor:
    id: 31
    init: 100000
    min: 0
    max: 1023;