(cl:defpackage dynamixel_manipulation-srv
  (:use )
  (:export
   "RESTARTCONTROLLER"
   "<RESTARTCONTROLLER-REQUEST>"
   "RESTARTCONTROLLER-REQUEST"
   "<RESTARTCONTROLLER-RESPONSE>"
   "RESTARTCONTROLLER-RESPONSE"
   "SETSPEED"
   "<SETSPEED-REQUEST>"
   "SETSPEED-REQUEST"
   "<SETSPEED-RESPONSE>"
   "SETSPEED-RESPONSE"
   "STARTCONTROLLER"
   "<STARTCONTROLLER-REQUEST>"
   "STARTCONTROLLER-REQUEST"
   "<STARTCONTROLLER-RESPONSE>"
   "STARTCONTROLLER-RESPONSE"
   "STOPCONTROLLER"
   "<STOPCONTROLLER-REQUEST>"
   "STOPCONTROLLER-REQUEST"
   "<STOPCONTROLLER-RESPONSE>"
   "STOPCONTROLLER-RESPONSE"
  ))

