// Generated by gencpp from file dynamixel_manipulation/RestartController.msg
// DO NOT EDIT!


#ifndef DYNAMIXEL_MANIPULATION_MESSAGE_RESTARTCONTROLLER_H
#define DYNAMIXEL_MANIPULATION_MESSAGE_RESTARTCONTROLLER_H

#include <ros/service_traits.h>


#include <dynamixel_manipulation/RestartControllerRequest.h>
#include <dynamixel_manipulation/RestartControllerResponse.h>


namespace dynamixel_manipulation
{

struct RestartController
{

typedef RestartControllerRequest Request;
typedef RestartControllerResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RestartController
} // namespace dynamixel_manipulation


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dynamixel_manipulation::RestartController > {
  static const char* value()
  {
    return "94c76c2df56346fcaa2611bdac54f434";
  }

  static const char* value(const ::dynamixel_manipulation::RestartController&) { return value(); }
};

template<>
struct DataType< ::dynamixel_manipulation::RestartController > {
  static const char* value()
  {
    return "dynamixel_manipulation/RestartController";
  }

  static const char* value(const ::dynamixel_manipulation::RestartController&) { return value(); }
};


// service_traits::MD5Sum< ::dynamixel_manipulation::RestartControllerRequest> should match
// service_traits::MD5Sum< ::dynamixel_manipulation::RestartController >
template<>
struct MD5Sum< ::dynamixel_manipulation::RestartControllerRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dynamixel_manipulation::RestartController >::value();
  }
  static const char* value(const ::dynamixel_manipulation::RestartControllerRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dynamixel_manipulation::RestartControllerRequest> should match
// service_traits::DataType< ::dynamixel_manipulation::RestartController >
template<>
struct DataType< ::dynamixel_manipulation::RestartControllerRequest>
{
  static const char* value()
  {
    return DataType< ::dynamixel_manipulation::RestartController >::value();
  }
  static const char* value(const ::dynamixel_manipulation::RestartControllerRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dynamixel_manipulation::RestartControllerResponse> should match
// service_traits::MD5Sum< ::dynamixel_manipulation::RestartController >
template<>
struct MD5Sum< ::dynamixel_manipulation::RestartControllerResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dynamixel_manipulation::RestartController >::value();
  }
  static const char* value(const ::dynamixel_manipulation::RestartControllerResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dynamixel_manipulation::RestartControllerResponse> should match
// service_traits::DataType< ::dynamixel_manipulation::RestartController >
template<>
struct DataType< ::dynamixel_manipulation::RestartControllerResponse>
{
  static const char* value()
  {
    return DataType< ::dynamixel_manipulation::RestartController >::value();
  }
  static const char* value(const ::dynamixel_manipulation::RestartControllerResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DYNAMIXEL_MANIPULATION_MESSAGE_RESTARTCONTROLLER_H
