// Generated by gencpp from file dynamixel_manipulation/SetSpeed.msg
// DO NOT EDIT!


#ifndef DYNAMIXEL_MANIPULATION_MESSAGE_SETSPEED_H
#define DYNAMIXEL_MANIPULATION_MESSAGE_SETSPEED_H

#include <ros/service_traits.h>


#include <dynamixel_manipulation/SetSpeedRequest.h>
#include <dynamixel_manipulation/SetSpeedResponse.h>


namespace dynamixel_manipulation
{

struct SetSpeed
{

typedef SetSpeedRequest Request;
typedef SetSpeedResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetSpeed
} // namespace dynamixel_manipulation


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dynamixel_manipulation::SetSpeed > {
  static const char* value()
  {
    return "4641bb0523a3557209606d9bd91ce33a";
  }

  static const char* value(const ::dynamixel_manipulation::SetSpeed&) { return value(); }
};

template<>
struct DataType< ::dynamixel_manipulation::SetSpeed > {
  static const char* value()
  {
    return "dynamixel_manipulation/SetSpeed";
  }

  static const char* value(const ::dynamixel_manipulation::SetSpeed&) { return value(); }
};


// service_traits::MD5Sum< ::dynamixel_manipulation::SetSpeedRequest> should match
// service_traits::MD5Sum< ::dynamixel_manipulation::SetSpeed >
template<>
struct MD5Sum< ::dynamixel_manipulation::SetSpeedRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dynamixel_manipulation::SetSpeed >::value();
  }
  static const char* value(const ::dynamixel_manipulation::SetSpeedRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dynamixel_manipulation::SetSpeedRequest> should match
// service_traits::DataType< ::dynamixel_manipulation::SetSpeed >
template<>
struct DataType< ::dynamixel_manipulation::SetSpeedRequest>
{
  static const char* value()
  {
    return DataType< ::dynamixel_manipulation::SetSpeed >::value();
  }
  static const char* value(const ::dynamixel_manipulation::SetSpeedRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dynamixel_manipulation::SetSpeedResponse> should match
// service_traits::MD5Sum< ::dynamixel_manipulation::SetSpeed >
template<>
struct MD5Sum< ::dynamixel_manipulation::SetSpeedResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dynamixel_manipulation::SetSpeed >::value();
  }
  static const char* value(const ::dynamixel_manipulation::SetSpeedResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dynamixel_manipulation::SetSpeedResponse> should match
// service_traits::DataType< ::dynamixel_manipulation::SetSpeed >
template<>
struct DataType< ::dynamixel_manipulation::SetSpeedResponse>
{
  static const char* value()
  {
    return DataType< ::dynamixel_manipulation::SetSpeed >::value();
  }
  static const char* value(const ::dynamixel_manipulation::SetSpeedResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DYNAMIXEL_MANIPULATION_MESSAGE_SETSPEED_H
