// Generated by gencpp from file dynamixel_manipulation/StopController.msg
// DO NOT EDIT!


#ifndef DYNAMIXEL_MANIPULATION_MESSAGE_STOPCONTROLLER_H
#define DYNAMIXEL_MANIPULATION_MESSAGE_STOPCONTROLLER_H

#include <ros/service_traits.h>


#include <dynamixel_manipulation/StopControllerRequest.h>
#include <dynamixel_manipulation/StopControllerResponse.h>


namespace dynamixel_manipulation
{

struct StopController
{

typedef StopControllerRequest Request;
typedef StopControllerResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct StopController
} // namespace dynamixel_manipulation


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dynamixel_manipulation::StopController > {
  static const char* value()
  {
    return "b3f1f861a8aef49071034d2f06308f6e";
  }

  static const char* value(const ::dynamixel_manipulation::StopController&) { return value(); }
};

template<>
struct DataType< ::dynamixel_manipulation::StopController > {
  static const char* value()
  {
    return "dynamixel_manipulation/StopController";
  }

  static const char* value(const ::dynamixel_manipulation::StopController&) { return value(); }
};


// service_traits::MD5Sum< ::dynamixel_manipulation::StopControllerRequest> should match 
// service_traits::MD5Sum< ::dynamixel_manipulation::StopController > 
template<>
struct MD5Sum< ::dynamixel_manipulation::StopControllerRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dynamixel_manipulation::StopController >::value();
  }
  static const char* value(const ::dynamixel_manipulation::StopControllerRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dynamixel_manipulation::StopControllerRequest> should match 
// service_traits::DataType< ::dynamixel_manipulation::StopController > 
template<>
struct DataType< ::dynamixel_manipulation::StopControllerRequest>
{
  static const char* value()
  {
    return DataType< ::dynamixel_manipulation::StopController >::value();
  }
  static const char* value(const ::dynamixel_manipulation::StopControllerRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dynamixel_manipulation::StopControllerResponse> should match 
// service_traits::MD5Sum< ::dynamixel_manipulation::StopController > 
template<>
struct MD5Sum< ::dynamixel_manipulation::StopControllerResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dynamixel_manipulation::StopController >::value();
  }
  static const char* value(const ::dynamixel_manipulation::StopControllerResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dynamixel_manipulation::StopControllerResponse> should match 
// service_traits::DataType< ::dynamixel_manipulation::StopController > 
template<>
struct DataType< ::dynamixel_manipulation::StopControllerResponse>
{
  static const char* value()
  {
    return DataType< ::dynamixel_manipulation::StopController >::value();
  }
  static const char* value(const ::dynamixel_manipulation::StopControllerResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DYNAMIXEL_MANIPULATION_MESSAGE_STOPCONTROLLER_H
