l_shoulder_pitch_controller:
  controller:
    package: dynamixel_manipulation
    module: joint_position_controller
    type: JointPositionController
  joint_name: l_shoulder_pitch_joint
  joint_speed: 1.17
  motor:
    id: 11
    init: 1000
    min: 0
    max: 1023